### ISSUE TITLE
Bugs about param_list acquisition

### ISSUE THREAD

**Issue by nbhgytzheng** [zeek/spicy-dhcp#9]
I found the bug while using this plugin (spicy-dhcp). line 88 of the file spicy-dhcp/analyzer/zeek_analyzer.spicy says the following code.
```
            for (value in values)
                values.push_back(cast<uint32>(value));
```
I think he should look like the following, otherwise he keeps returning null values, because values was just declared at line 86.
```
            for (value in option.request_values)
                values.push_back(cast<uint32>(value));
```
I tried this modification and he was able to fetch the param_list correctly .

**Comment by bbannier** [comment]
Thank you for the report and the proposed fix. I have applied basically your suggested changes and released a new version `spicy-dhcp-0.0.6`.
